server:
  port: 8080

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/sys
    username: root
    password: 1234
    hikari:
            connectionTimeout : 30000
            maximumPoolSize : 10
            maxLifetime : 1800000
            poolName : HikariCP
            readOnly : false
            connectionTestQuery : SELECT 1
    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      #      show_sql: true
      format_sql: true
        
security:
  user:
    name: user
    password: user1257dsecret

mybatis:
  mapper-locations: mapper/*.xml

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
  
#jwt.secret=7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=
#jwt.access-token-validity-in-seconds=6
#jwt.refresh-token-validity-in-seconds=6

#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3306/sys
#spring.datasource.username=root
#spring.datasource.password=1234

#mybatis.mapper-locations=classpath:mapper/*.xml

#spring.jpa.hibernate.ddl-auto=update  
#spring.jpa.properties.hibernate.format_sql=true  
#spring.jpa.show-sql=true  
